let data;
let page = 'home';
let assortmentTab = 'minerals_crystals';
let draft = { name: '', theme: 'Glacier', items: [], notes: '' };
const app = document.querySelector('#app');
const sectionLabels = { minerals_crystals: '水晶 / 矿物', pearls_organic: '珍珠 / 天然材质', hardware_accessories: '配饰 / 结构件', packaging: '包装' };
const tierLabels = { A_CORE: '核心常备', B_DESIGN_EXTENSION: '设计扩展', C_SIGNATURE_ONE_OF_ONE: 'Signature / 孤品', RESERVE_NOT_CORE: '备用' };
const chineseNames = { 'Clear Quartz':'白水晶', 'Smoky Quartz':'茶晶', 'Aquamarine':'海蓝宝', 'Labradorite':'拉长石', 'Rainbow Moonstone':'彩虹月光石', 'Amazonite':'天河石', 'Lapis Lazuli':'青金石', 'Green Phantom Quartz':'绿幽灵', 'Obsidian':'黑曜石', 'Amethyst':'紫水晶', 'Citrine':'黄水晶', "Tiger's Eye":'虎眼石', 'Blue Lace Agate':'蓝纹玛瑙', 'Kunzite':'锂辉石', 'Bloodstone':'血石', 'White Phantom Quartz':'白幽灵', 'Rose Quartz':'粉水晶', 'Rainbow Obsidian':'彩虹黑曜石', 'Larimar':'海纹石', 'Gold Rutilated Quartz':'金发晶', 'Black Rutilated Quartz':'黑发晶', 'Rutilated Quartz':'发晶', 'Sugilite':'舒俱来', 'Aquamarine / collector focal grade':'海蓝宝 / 收藏级主石' };
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (x) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[x]));
const label = (value, map) => map[value] || value;
const itemName = (item) => item.name || item.canonical_name || item.component_code || item.packaging_code || '未命名选项';
const bilingualName = (item) => chineseNames[itemName(item)] ? `${chineseNames[itemName(item)]} <small>${esc(itemName(item))}</small>` : esc(itemName(item));
const designSentence = (item) => item.selection_notes || item.description || item.material_description || item.notes || '用于构成设计的一个可选元素。';
const tags = (items = []) => items.map((x) => `<span class="tag">${esc(x)}</span>`).join('');
function selectOptions(values, map = {}) { return values.map((x) => `<option value="${esc(x)}">${esc(label(x, map))}</option>`).join(''); }
function setPage(next) { page = next; document.querySelectorAll('.nav-item').forEach((button) => button.classList.toggle('active', button.dataset.page === page)); render(); }
function addToDesk(name) { const source = data.assortment.items.find((item) => item.name === name); if (!source || draft.items.some((item) => item.name === name)) return; draft.items.push({ ...source, role: source.roles?.[0] || '', form: source.preferred_forms?.[0] || '' }); setPage('desk'); }
function render() { renderSidePreview(); if (page === 'home') return renderHome(); if (page === 'assortment') return renderAssortment(); if (page === 'inspiration') return renderInspiration(); return renderDesk(); }
function renderSidePreview() { const accessory = document.querySelector('#accessory-preview'); const packaging = document.querySelector('#packaging-preview'); if (!accessory || !data) return; accessory.innerHTML = data.assortment.items.filter((x) => x.section === 'hardware_accessories').slice(0, 6).map((x) => `<div class="mini-object"><i>○</i><span>${esc(x.name.replace('925 sterling silver ', '').replace('925 sterling silver', '银'))}</span></div>`).join(''); packaging.innerHTML = data.assortment.items.filter((x) => x.section === 'packaging').slice(0, 6).map((x) => `<div class="mini-object"><i>□</i><span>${esc(x.name.replace('Compact ', '').replace('presentation ', ''))}</span></div>`).join(''); }
function renderHome() {
  const byTier = data.overview.assortmentByPriority;
  app.innerHTML = `<section class="desktop-panel"><div class="panel-title">水晶目录 <b>×</b></div><section class="page-head"><div><h1>水晶设计工作台</h1><p>选材料、找灵感、做设计。</p></div></section>
  <section class="action-grid"><button class="action-card" data-go="assortment"><strong>开始选品</strong><span>从水晶、天然材质、配饰和包装中挑选。</span></button><button class="action-card" data-go="inspiration"><strong>查看灵感</strong><span>查看已经整理的设计参考和主题语言。</span></button><button class="action-card" data-go="desk"><strong>开始设计</strong><span>建立一个新的手串设计草稿。</span></button></section>
  <section class="summary-strip"><div><b>${byTier.A_CORE || 0}</b><span>核心选品</span></div><div><b>${byTier.B_DESIGN_EXTENSION || 0}</b><span>设计扩展</span></div><div><b>${byTier.C_SIGNATURE_ONE_OF_ONE || 0}</b><span>Signature / 孤品</span></div><div><b>—</b><span>最近设计草稿</span></div></section>
  <section class="next-step"><h2>下一步</h2><p>先从选品库挑选一个材料或配饰，再到设计台调整它的角色与规格。</p><button class="primary" data-go="assortment">进入选品库</button></section></section>`;
  app.querySelectorAll('[data-go]').forEach((button) => button.onclick = () => setPage(button.dataset.go));
}
function renderAssortment() {
  const allSections = Object.keys(sectionLabels);
  app.innerHTML = `<section class="desktop-panel"><div class="panel-title">水晶目录 <b>×</b></div><section class="page-head"><div><h1>${sectionLabels[assortmentTab]}</h1><p>圆珠展示图优先；每个选项均提供中文主名与英文对照。</p></div><div class="export-actions"><button id="exportCsv">导出当前选品 CSV</button><button id="exportJson">导出当前选品 JSON</button></div></section><div class="segmented">${allSections.map((section) => `<button class="${section === assortmentTab ? 'selected' : ''}" data-section="${section}">${sectionLabels[section]}</button>`).join('')}</div><div class="filters"><label>搜索：<input id="search" placeholder="材料名称"></label><label>主题：<select id="theme"><option value="">全部</option>${selectOptions(data.overview.themes)}</select></label><label>形状：<input id="form" placeholder="全部"></label><label>层级：<select id="tier"><option value="">全部</option>${selectOptions(Object.keys(tierLabels), tierLabels)}</select></label><button id="clear">清除筛选</button></div><div id="selection-list" class="catalog classic-catalog"></div></section>`;
  app.querySelectorAll('[data-section]').forEach((button) => button.onclick = () => { assortmentTab = button.dataset.section; renderAssortment(); });
  const draw = () => { const theme = app.querySelector('#theme').value; const tier = app.querySelector('#tier').value; const form = app.querySelector('#form').value.toLowerCase(); const search = app.querySelector('#search').value.toLowerCase(); const rows = data.assortment.items.filter((item) => item.section === assortmentTab && (!theme || item.themes.includes(theme)) && (!tier || item.priority === tier) && (!form || item.preferred_forms.join(' ').toLowerCase().includes(form)) && (!search || JSON.stringify(item).toLowerCase().includes(search))); app.querySelector('#selection-list').innerHTML = rows.length ? rows.map((item) => `<article class="selection-card classic-card"><h2>${bilingualName(item)}</h2><div class="round-bead-pending"><span>○</span><em>待补圆珠实拍图</em></div><div class="shape-strip"><i>○</i><i>◇</i><i>▣</i></div><p>${esc(designSentence(item))}</p><p class="spec"><b>推荐规格：</b>${esc(item.preferred_forms.join(' · '))}</p>${tags(item.themes)}<span class="tier">${esc(label(item.priority, tierLabels))}</span><button class="primary" data-add="${esc(item.name)}">加入设计台</button><details><summary>查看详情</summary><p>${item.identity_status === 'canonical_match' ? '已匹配到项目材料库。' : '当前作为选品候选存在。'}</p></details></article>`).join('') : '<p class="empty">没有符合条件的选项。试试放宽筛选。</p>'; app.querySelectorAll('[data-add]').forEach((button) => button.onclick = () => addToDesk(button.dataset.add)); };
  app.querySelectorAll('.filters input,.filters select').forEach((element) => element.oninput = draw); app.querySelector('#clear').onclick = () => { app.querySelectorAll('.filters input').forEach((x) => x.value = ''); app.querySelectorAll('.filters select').forEach((x) => x.value = ''); draw(); }; draw();
  app.querySelector('#exportCsv').onclick = () => exportAssortment('csv'); app.querySelector('#exportJson').onclick = () => exportAssortment('json');
}
function renderInspiration() {
  app.innerHTML = `<section class="page-head"><div><h1>灵感库</h1><p>从已整理的设计参考中提取主题、氛围和结构语言。</p></div></section><div class="filters"><select id="theme"><option value="">全部主题</option>${selectOptions(data.overview.themes)}</select><input id="search" placeholder="搜索设计语言"></div><div id="reference-list" class="catalog"></div>`;
  const draw = () => { const theme = app.querySelector('#theme').value; const search = app.querySelector('#search').value.toLowerCase(); const rows = data.references.filter((ref) => (!theme || ref.themes.includes(theme)) && (!search || JSON.stringify(ref).toLowerCase().includes(search))); app.querySelector('#reference-list').innerHTML = rows.map((ref) => `<article class="reference-card"><div class="image-placeholder">参考图<br>已整理</div><div><h2>${esc(ref.title || '设计参考')}</h2><p>${esc(ref.snippets?.[0]?.value || ref.notes || '已保存的视觉参考，可用于理解设计语言。')}</p>${tags(ref.themes)}<small>${ref.asset_count} 张相关图片</small></div></article>`).join('') || '<p class="empty">没有符合条件的灵感参考。</p>'; };
  app.querySelectorAll('.filters input,.filters select').forEach((element) => element.oninput = draw); draw();
}
async function renderDesk() {
  const result = await fetch('/api/drafts').then((response) => response.json());
  app.innerHTML = `<section class="page-head"><div><h1>设计台</h1><p>把选品组织成一个可保存、可导出的手串设计草稿。</p></div></section><section class="desk-panel"><div class="desk-controls"><label>设计名称<input id="draft-name" value="${esc(draft.name)}" placeholder="例如：冰川晨光"></label><label>主题<select id="draft-theme">${selectOptions(data.overview.themes).replace(`value="${draft.theme}"`, `value="${draft.theme}" selected`)}</select></label><label>载入草稿<select id="draft-load"><option value="">选择已有草稿</option>${result.drafts.map((name) => `<option>${esc(name)}</option>`).join('')}</select></label></div><label>设计备注<textarea id="draft-notes" placeholder="记录这套设计的氛围、组合理由或待确认事项。">${esc(draft.notes)}</textarea></label><div class="desk-toolbar"><button id="open-selection">添加材料</button><button id="save-draft" class="primary">保存草稿</button><button id="export-draft">导出设计单</button></div><p id="desk-status" class="status"></p><div id="draft-items"></div></section>`;
  const sync = () => { draft.name = app.querySelector('#draft-name').value; draft.theme = app.querySelector('#draft-theme').value; draft.notes = app.querySelector('#draft-notes').value; const container = app.querySelector('#draft-items'); if (!draft.items.length) { container.innerHTML = '<p class="empty">还没有材料。去选品库添加，或点击“添加材料”。</p>'; return; } container.innerHTML = draft.items.map((item, index) => `<div class="draft-item"><b>${esc(item.name)}</b><label>角色<input data-role="${index}" value="${esc(item.role || '')}"></label><label>规格 / 形状<input data-form="${index}" value="${esc(item.form || '')}"></label><button data-up="${index}">上移</button><button data-down="${index}">下移</button><button data-remove="${index}">删除</button></div>`).join(''); container.querySelectorAll('[data-role]').forEach((input) => input.oninput = () => draft.items[Number(input.dataset.role)].role = input.value); container.querySelectorAll('[data-form]').forEach((input) => input.oninput = () => draft.items[Number(input.dataset.form)].form = input.value); container.querySelectorAll('[data-up]').forEach((button) => button.onclick = () => { const i = Number(button.dataset.up); if (i) [draft.items[i - 1], draft.items[i]] = [draft.items[i], draft.items[i - 1]]; sync(); }); container.querySelectorAll('[data-down]').forEach((button) => button.onclick = () => { const i = Number(button.dataset.down); if (i < draft.items.length - 1) [draft.items[i + 1], draft.items[i]] = [draft.items[i], draft.items[i + 1]]; sync(); }); container.querySelectorAll('[data-remove]').forEach((button) => button.onclick = () => { draft.items.splice(Number(button.dataset.remove), 1); sync(); }); };
  sync(); app.querySelector('#open-selection').onclick = () => setPage('assortment'); app.querySelector('#save-draft').onclick = async () => { sync(); const status = app.querySelector('#desk-status'); if (!draft.name.trim()) return status.textContent = '请先填写设计名称。'; const response = await fetch(`/api/drafts/${encodeURIComponent(draft.name)}`, { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify(draft) }); status.textContent = response.ok ? '草稿已保存。' : '保存失败，请检查设计名称。'; }; app.querySelector('#draft-load').onchange = async (event) => { if (!event.target.value) return; const response = await fetch(`/api/drafts/${encodeURIComponent(event.target.value)}`); const body = await response.json(); if (!response.ok) return app.querySelector('#desk-status').textContent = body.error?.message || '无法读取草稿。'; draft = body; renderDesk(); }; app.querySelector('#export-draft').onclick = async () => { sync(); if (!draft.name.trim()) return app.querySelector('#desk-status').textContent = '请先保存并命名草稿。'; const response = await fetch(`/api/drafts/${encodeURIComponent(draft.name)}/export`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ format: 'md' }) }); app.querySelector('#desk-status').textContent = response.ok ? '设计单已导出到 workbench/exports。' : '导出失败，请先保存草稿。'; };
}
async function exportAssortment(format) { const response = await fetch(`/api/export/assortment?format=${format}`); const body = await response.json(); if (!response.ok) return alert('导出失败。'); alert(`已导出到：${body.path}`); }
document.querySelectorAll('[data-page]').forEach((button) => button.onclick = () => setPage(button.dataset.page));
document.querySelector('#toolbar-export').onclick = () => exportAssortment('csv');
fetch('/api/data').then((response) => response.json()).then((body) => { data = body; render(); }).catch(() => { app.textContent = '无法加载工作台数据，请确认本地服务已启动。'; });
